name: Validate JSONs

on: [pull_request, push]

jobs:
    verify-json-locations:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Validate locations
              uses: docker://orrosenblatt/validate-json-action:latest
              env:
                  INPUT_SCHEMA: /templates/.schemas/locations.schema.json
                  INPUT_JSONS: /locations.json

    verify-json-articles:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Validate articles
              uses: docker://orrosenblatt/validate-json-action:latest
              env:
                  INPUT_SCHEMA: /templates/.schemas/articles.schema.json
                  INPUT_JSONS: /articles.json

    verify-json-tour_locations:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Validate tour locations
              uses: docker://orrosenblatt/validate-json-action:latest
              env:
                  INPUT_SCHEMA: /templates/.schemas/tour_locations.schema.json
                  INPUT_JSONS: /tour_locations.json

    verify-json-offerings:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Validate tour locations
              uses: docker://orrosenblatt/validate-json-action:latest
              env:
                  INPUT_SCHEMA: /templates/.schemas/offerings.schema.json
                  INPUT_JSONS: /offerings.json

    # News:

    verify-json-news-health:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Validate news
              uses: docker://orrosenblatt/validate-json-action:latest
              env:
                  INPUT_SCHEMA: /templates/.schemas/news-health.schema.json
                  INPUT_JSONS: /news-health.json

    verify-json-news-repeat:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Validate news
              uses: docker://orrosenblatt/validate-json-action:latest
              env:
                  INPUT_SCHEMA: /templates/.schemas/news.schema.json
                  INPUT_JSONS: /news-repeat.json

    # Years: ------------------------------------------------------------------

    verify-json-news-2028:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Validate news
              uses: docker://orrosenblatt/validate-json-action:latest
              env:
                  INPUT_SCHEMA: /templates/.schemas/news.schema.json
                  INPUT_JSONS: /news-2028.json

    verify-json-news-2027:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Validate news
              uses: docker://orrosenblatt/validate-json-action:latest
              env:
                  INPUT_SCHEMA: /templates/.schemas/news.schema.json
                  INPUT_JSONS: /news-2027.json

    verify-json-news-2026:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Validate news
              uses: docker://orrosenblatt/validate-json-action:latest
              env:
                  INPUT_SCHEMA: /templates/.schemas/news.schema.json
                  INPUT_JSONS: /news-2026.json

    verify-json-news-2025:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Validate news
              uses: docker://orrosenblatt/validate-json-action:latest
              env:
                  INPUT_SCHEMA: /templates/.schemas/news.schema.json
                  INPUT_JSONS: /news-2025.json

    verify-json-news-2024:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Validate news
              uses: docker://orrosenblatt/validate-json-action:latest
              env:
                  INPUT_SCHEMA: /templates/.schemas/news.schema.json
                  INPUT_JSONS: /news-2024.json

    verify-json-news-2023:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Validate news
              uses: docker://orrosenblatt/validate-json-action:latest
              env:
                  INPUT_SCHEMA: /templates/.schemas/news.schema.json
                  INPUT_JSONS: /news-2023.json
