name: Validate JSONs

on: [pull_request, push]

jobs:
  verify-json-locations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate locations
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /templates/.schemas/locations.schema.json
          INPUT_JSONS: /locations.json

  verify-json-news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate news
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /templates/.schemas/news.schema.json
          INPUT_JSONS: /news.json

  verify-json-articles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate articles
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /templates/.schemas/articles.schema.json
          INPUT_JSONS: /articles.json

  verify-json-tour_locations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate tour locations
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /templates/.schemas/tour_locations.schema.json
          INPUT_JSONS: /tour_locations.json
  verify-json-offerings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate tour locations
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /templates/.schemas/offerings.schema.json
          INPUT_JSONS: /offerings.json
